### ISSUE TITLE
Website setup

### ISSUE THREAD

**Issue by user2222222222** [ret2got/disasm.ninja#7]
It would be really great to have instructions on how to set this up on a web server.  I was able to get disasm installed and python3 ninja.py launches ok, but can't figure out how to get the web page part of it setup.  The index.py tries to load a lib that doesn't exist.  Not sure how to get Socket.io to communicate with the server.  This was really a useful tool and sad that it's gone.  Thanks

**Comment by ret2jazzy** [comment]
Hi @user2222222222, I'm sorry my domain had a lot of issues. It should be back up now

**Comment by user2222222222** [comment]
Awesome, thank you!

**Comment by user2222222222** [comment]
The domain is down again: it's a great tool

http://disasm.pro/

**Comment by user2222222222** [comment]
Fixed again, thanks so much!
